[stats]
distro       = { icon = " ", name = "distro", color = "(GN)" }
desktop      = { icon = " ", name = "desktop", color = "(CN)" }
kernel       = { icon = " ", name = "kernel", color = "(MA)" }
shell        = { icon = " ", name = "shell", color = "(MA)" }
packages     = { icon = " ", name = "packages", color = "(RD)" }
sep_hardware = "SEPARATOR"
cpu          = { icon = " ", name = "cpu", color = "(RD)" }
gpu          = { icon = "󱔐 ", name = "gpu", color = "(MA)" }
memory       = { icon = " ", name = "memory", color = "(YW)" }
disk_0       = { icon = " ", name = "disk", color = "(GN)" }
sep_color    = "SEPARATOR"
colors       = { icon = " ", name = "colors", color = "!DT!", symbol = "" }

[misc]
borderstyle = "line"
layout      = "Inline"

[misc.figletLogos]
enable = false
color  = ""
font   = ""
margin = [0, 0, 0,]

[misc.imageMode]
enable = false
path   = ""
scale  = 1
margin = [0, 0, 0,]
