[arch]
alias = "default"
margin = [3, 2, 3]
art = [
    "{BE}      /\\      ",
    "{BE}     /  \\     ",
    "{BE}    /\\   \\    ",
    "{BE}   /      \\   ",
    "{BE}  /   ,,   \\  ",
    "{BE} /   |  |  -\\ ",
    "{BE}/_-''    ''-_\\",
]
