config_version = 13

[audio]
enable_sounds = true

[backdrop]
blur_intensity = 0.19999999552965164
enabled = true

[bar.default]
capsule = true
center = [ "weather", "clock", "group:g2" ]
contact_shadow = true
end = [ "group:g4", "tray", "group:g1", "group:g6" ]
layer = "overlay"
reserve_space = false
smart_auto_hide = true
start = [ "group:g3", "group:g5" ]

    [[bar.default.capsule_group]]
    accordion = true
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g2"
    members = [ "session", "clipboard", "todo", "widget", "bar" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    accordion = true
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g3"
    members = [ "workspaces", "active_window" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    accordion = true
    accordion_direction = "start"
    enabled = true
    fill = "surface_variant"
    id = "g4"
    members = [ "sysmon", "bar_2" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g1"
    members = [ "network", "bluetooth", "volume", "battery", "privacy" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g5"
    members = [ "audio_visualizer", "media" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g6"
    members = [ "widget_2", "notifications" ]
    opacity = 1.0
    padding = 6.0

[brightness]
enable_ddcutil = true

[calendar]
enabled = true

    [calendar.account.personal_google]
    name = "Google"
    type = "google"

[control_center]
sidebar = "full"

    [control_center.calendar]
    show_events_card = false
    show_week_numbers = true

[desktop_widgets]
schema_version = 2
widget_order = [
    "desktop-widget-0000000000000001",
    "desktop-widget-0000000000000006",
    "desktop-widget-0000000000000007",
    "desktop-widget-0000000000000008"
]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 0.0
    box_width = 0.0
    cx = 1844.0
    cy = 194.0
    output = "DP-1"
    placement_height = 1152.0
    placement_width = 2048.0
    rotation = 0.0
    type = "weather"

    [desktop_widgets.widget.desktop-widget-0000000000000006]
    box_height = 0.0
    box_width = 0.0
    cx = 1756.0
    cy = 924.0
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-0000000000000006.settings]
        stat = "cpu_usage"
        stat2 = "cpu_temp"

    [desktop_widgets.widget.desktop-widget-0000000000000007]
    box_height = 0.0
    box_width = 0.0
    cx = 1600.0
    cy = 960.5
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-0000000000000007.settings]
        background = true
        background_color = "surface"
        background_opacity = 0.80000000000000004
        background_padding = 10
        background_radius = 12
        color = "primary"
        color2 = "secondary"
        display = "gauge"
        font_family = ""
        gauge_layout = "horizontal"
        highlight_color = "error"
        interface = ""
        label_min_width = 0
        network_speed_compact = false
        network_speed_unit = "auto"
        shadow = true
        show_label = true
        stat = "net_tx"
        stat2 = ""

    [desktop_widgets.widget.desktop-widget-0000000000000008]
    box_height = 0.0
    box_width = 0.0
    cx = 1600.0
    cy = 896.5
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-0000000000000008.settings]
        background = true
        background_color = "surface"
        background_opacity = 0.80000000000000004
        background_padding = 10
        background_radius = 12
        color = "primary"
        color2 = "secondary"
        display = "gauge"
        font_family = ""
        gauge_layout = "horizontal"
        highlight_color = "error"
        interface = ""
        label_min_width = 0
        network_speed_compact = false
        network_speed_unit = "auto"
        shadow = true
        show_label = true
        stat = "net_rx"
        stat2 = ""

[dock]
enabled = true
icon_size = 36
launcher_icon = "rocket"
launcher_position = "start"
pinned = [ "helium", "org.gnome.Nautilus" ]
reserve_space = false
show_dots = true
smart_auto_hide = true

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 1800.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 900.0

[location]
auto_locate = true

[lockscreen]
blurred_desktop = true

[lockscreen_widgets]
enabled = true
schema_version = 1
widget_order = [
    "lockscreen-login-box@DP-1",
    "lockscreen-login-box@HDMI-A-1",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000002",
    "lockscreen-widget-0000000000000003"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 196.0
    box_width = 720.0
    cx = 1024.0
    cy = 983.5
    output = "DP-1"
    placement_height = 1152.0
    placement_width = 2048.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        center_password_text = false
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 720.0
    cx = 960.0
    cy = 957.0
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        center_password_text = false
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 144.0
    box_width = 304.0
    cx = 1024.0
    cy = 184.0
    output = "DP-1"
    placement_height = 1152.0
    placement_width = 2048.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background_opacity = 0.59999999999999998
        center_text = false
        clock_style = "digital"
        shadow = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 0.0
    box_width = 0.0
    cx = 1796.0
    cy = 130.0
    output = "DP-1"
    placement_height = 1152.0
    placement_width = 2048.0
    rotation = 0.0
    type = "weather"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
    box_height = 0.0
    box_width = 0.0
    cx = 1805.0
    cy = 1014.0
    output = "DP-1"
    placement_height = 1152.0
    placement_width = 2048.0
    rotation = 0.0
    type = "media_player"

[nightlight]
enabled = true

[notification]
history_retention_hours = 24
layer = "overlay"

[osd]
background_opacity = 0.4999999888241291
orientation = "vertical"
position_vertical = "center_right"
scale = 0.90000000596046448

[plugin_settings."davemhammer/tailscale"]
notify_on_peer_change = false

[plugin_settings."goatnath/spotify-lyrics"]
lyrics-panel_placement = "attached"

[plugin_settings."h465855hgg/lyrics"]
lyrics_sources = [ "spotify", "lrclib", "netease", "splayer", "qqmusic", "kugou", "qishui", "apple_music", "musixmatch" ]
translation_language = "zh-Hant"

[plugin_settings."noctalia/translator"]
target_lang = "en"

[plugin_settings."nzlov/daily-wallpaper"]
source = "nasa"

[plugin_settings."yuuto/arch-updater"]
auto_check_hours = 1
notify_on_updates = false
show_activity_graph = true

[plugins]
enabled = [
    "lucasoe/proton-pass",
    "noctalia/timer",
    "nightwatch75/todo",
    "ramosdetrigo/godot-provider",
    "oldirtty/color_picker",
    "h465855hgg/lyrics",
    "yuuto/arch-updater",
    "rylos/tailnet",
    "rylos/syncthing"
]

[shell]
avatar_path = "/home/mono/.avatar.webp"
clipboard_confirm_clear_history = false
external_ip_enabled = true
polkit_agent = true
screen_time_enabled = true
settings_show_advanced = true
settings_window_translucent = true
telemetry_enabled = true

    [shell.greeter_sync]
    auto_sync = true

    [shell.launcher]
    app_grid = true
    pinned = [ "dev.zed.Zed", "AppFlowy", "org.godotengine.Godot", "spotify-launcher", "steam" ]
    show_app_actions = true

    [shell.panel]
    open_near_click_control_center = true
    transparency_mode = "glass"

    [shell.screen_corners]
    enabled = true

    [shell.screenshot]
    confirm_region = true

    [shell.session]
    show_shortcuts = false

        [[shell.session.actions]]
        action = "lock"
        countdown_seconds = 0.0
        enabled = true
        shortcut = "1"
        variant = "default"

        [[shell.session.actions]]
        action = "logout"
        countdown_seconds = 1.0
        enabled = true
        shortcut = "2"
        variant = "default"

        [[shell.session.actions]]
        action = "lock_and_suspend"
        countdown_seconds = 1.0
        enabled = true
        shortcut = "3"
        variant = "default"

        [[shell.session.actions]]
        action = "reboot"
        countdown_seconds = 5.0
        enabled = true
        shortcut = "4"
        variant = "default"

        [[shell.session.actions]]
        action = "shutdown"
        countdown_seconds = 5.0
        enabled = true
        shortcut = "5"
        variant = "destructive"

[theme]
builtin = "Ayu"
community_palette = "Noctalia legacy"
source = "wallpaper"
wallpaper_scheme = "m3-content"

    [theme.templates]
    enable_builtin_templates = false
    enable_community_templates = false

[wallpaper]
directory = "/home/mono/.config/niri/assets"

    [wallpaper.default]
    path = "/home/mono/.config/niri/assets/wallpaper.jpg"

    [wallpaper.last]
    path = "/home/mono/.config/niri/assets/wallpaper.jpg"

    [wallpaper.monitors.DP-1]
    path = "/home/mono/.config/niri/assets/wallpaper.jpg"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/mono/.config/niri/assets/wallpaper.jpg"

[widget.active_window]
display = "text_only"
title_scroll = "on_hover"

[widget.bar]
show_idle_on_horizontal = false
type = "noctalia/timer:bar"

[widget.bar_2]
type = "rylos/tailnet:bar"

[widget.bluetooth]
hide_when_no_connected_device = true

[widget.cat]
type = "noctalia/bongocat:cat"

[widget.clock]
anchor = true
tooltip_format = "{:%Y/%m/%d}"

[widget.keyboard_layout]
display = "full"

[widget.media]
art_size = 96
hide_when_no_media = true

[widget.network]
show_label = false

[widget.privacy]
hide_inactive = true

[widget.session]
capsule = true

[widget.sysmon.actions]
right = "exec missioncenter"

[widget.todo]
type = "nightwatch75/todo:todo"

[widget.tray]
drawer = true
drawer_columns = 5
pinned = [ "Fcitx", "Vesktop" ]

[widget.weather]
show_condition = false

[widget.widget]
type = "oldirtty/color_picker:widget"

[widget.widget_2]
hide_on_empty = true
type = "yuuto/arch-updater:widget"

[widget.workspaces]
hide_when_empty = true
show_labels = false
style = "focus_hint"

    [widget.workspaces.actions]
    back = "workspace-switch next"
    forward = "workspace-switch prev"
    right = "exec niri msg action toggle-overview"
    scroll_down = "exec niri msg action focus-column-right"
    scroll_up = "exec niri msg action focus-column-left"