[[language]]
name = "toml"
formatter = { command = "taplo", args = ["format", "-"] }
auto-format = true

[[language]]
name = "fish"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "html"
formatter = { command = "prettier", args = ["--stdin-filepath", ".html"] }
[[language]]
name = "json"
formatter = { command = "prettier", args = ["--stdin-filepath", ".json"] }
[[language]]
name = "css"
formatter = { command = "prettier", args = ["--stdin-filepath", ".css"] }
[[language]]
name = "scss"
formatter = { command = "prettier", args = ["--stdin-filepath", ".scss"] }
[[language]]
name = "javascript"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "prettier", args = ["--stdin-filepath", ".js"] }
auto-format = true
[[language]]
name = "typescript"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "prettier", args = ["--stdin-filepath", ".ts"] }
auto-format = true


[[language]]
name = "gdscript"
formatter = { command = "gdformat", args = ["-"] }
auto-format = true


[[language]]
name = "typst"
formatter = { command = "typstfmt", args = ["--output", "-"] }
auto-format = true
