IgnorePath "*.cache"
IgnorePath "*.lock"

IgnorePath "/usr/*"
IgnorePath "/var/*"
IgnorePath "/opt/*"

# Boot
IgnorePath "/boot/vmlinuz-linux*"
IgnorePath "/boot/*.img"
# Snapper
IgnorePath "/.snapshots/*"
IgnorePath "/etc/conf.d/snapper"
IgnorePath "/etc/snapper"

## ETC
IgnorePath "/etc/ca-certificates/*"
IgnorePath "/etc/fonts/*"
IgnorePath "/etc/spotify-launcher.conf"
IgnorePath "/etc/fwupd/*"
# Network
IgnorePath "/etc/NetworkManager/system-connections/*"
# Pacman
IgnorePath "/etc/pacman.d/gnupg/*"
IgnorePath "/etc/pacman.d/*mirrorlist*"
# SSH
IgnorePath "/etc/ssh/*"
IgnorePath "/etc/ssl/*"
# Systemd
IgnorePath "/etc/systemd/system/*"
IgnorePath "/etc/systemd/user/*"
IgnorePath "/etc/userdb"
IgnorePath "/etc/vconsole.conf"
IgnorePath "/etc/.updated"
# Tailscale
IgnorePath "/etc/resolv.conf"
IgnorePath "/etc/resolv.pre-tailscale-backup.conf"
# System File
IgnorePath "/etc/audisp"
IgnorePath "/etc/audit"
IgnorePath "/etc/cni/net.d"
IgnorePath "/etc/fstab"
IgnorePath "/etc/group"
IgnorePath "/etc/gshadow"
IgnorePath "/etc/hostname"
IgnorePath "/etc/machine-id"
IgnorePath "/etc/os-release"
IgnorePath "/etc/passwd*"
IgnorePath "/etc/shadow"
IgnorePath "/etc/subgid"
IgnorePath "/etc/subuid"
IgnorePath "/etc/sudoers*"
IgnorePath "/etc/xml"
IgnorePath "/etc/*-"
