AddPackage refind # An EFI boot manager

CopyFile /efi/EFI/Arch/refind_linux.conf 755
CopyFile /efi/EFI/refind/BOOT.CSV 755
CopyFile /efi/EFI/refind/drivers_x64/btrfs_x64.efi 755
CopyFile /efi/EFI/refind/drivers_x64/ext2_x64.efi 755
CopyFile /efi/EFI/refind/drivers_x64/ext4_x64.efi 755
CopyFile /efi/EFI/refind/drivers_x64/hfs_x64.efi 755
CopyFile /efi/EFI/refind/drivers_x64/iso9660_x64.efi 755
CopyFile /efi/EFI/refind/drivers_x64/reiserfs_x64.efi 755
CopyFile /efi/EFI/refind/icons/arrow_left.png 755
CopyFile /efi/EFI/refind/icons/arrow_right.png 755
CopyFile /efi/EFI/refind/icons/boot_linux.png 755
CopyFile /efi/EFI/refind/icons/boot_win.png 755
CopyFile /efi/EFI/refind/icons/func_about.png 755
CopyFile /efi/EFI/refind/icons/func_bootorder.png 755
CopyFile /efi/EFI/refind/icons/func_csr_rotate.png 755
CopyFile /efi/EFI/refind/icons/func_exit.png 755
CopyFile /efi/EFI/refind/icons/func_firmware.png 755
CopyFile /efi/EFI/refind/icons/func_hidden.png 755
CopyFile /efi/EFI/refind/icons/func_install.png 755
CopyFile /efi/EFI/refind/icons/func_reset.png 755
CopyFile /efi/EFI/refind/icons/func_shutdown.png 755
CopyFile /efi/EFI/refind/icons/mouse.png 755
CopyFile /efi/EFI/refind/icons/os_arch.png 755
CopyFile /efi/EFI/refind/icons/os_artful.png 755
CopyFile /efi/EFI/refind/icons/os_bionic.png 755
CopyFile /efi/EFI/refind/icons/os_centos.png 755
CopyFile /efi/EFI/refind/icons/os_chakra.png 755
CopyFile /efi/EFI/refind/icons/os_chrome.png 755
CopyFile /efi/EFI/refind/icons/os_clover.png 755
CopyFile /efi/EFI/refind/icons/os_crunchbang.png 755
CopyFile /efi/EFI/refind/icons/os_debian.png 755
CopyFile /efi/EFI/refind/icons/os_devuan.png 755
CopyFile /efi/EFI/refind/icons/os_elementary.png 755
CopyFile /efi/EFI/refind/icons/os_fedora.png 755
CopyFile /efi/EFI/refind/icons/os_freebsd.png 755
CopyFile /efi/EFI/refind/icons/os_frugalware.png 755
CopyFile /efi/EFI/refind/icons/os_gentoo.png 755
CopyFile /efi/EFI/refind/icons/os_gummiboot.png 755
CopyFile /efi/EFI/refind/icons/os_haiku.png 755
CopyFile /efi/EFI/refind/icons/os_hwtest.png 755
CopyFile /efi/EFI/refind/icons/os_kubuntu.png 755
CopyFile /efi/EFI/refind/icons/os_legacy.png 755
CopyFile /efi/EFI/refind/icons/os_linux.png 755
CopyFile /efi/EFI/refind/icons/os_linuxmint.png 755
CopyFile /efi/EFI/refind/icons/os_lubuntu.png 755
CopyFile /efi/EFI/refind/icons/os_mac.png 755
CopyFile /efi/EFI/refind/icons/os_mageia.png 755
CopyFile /efi/EFI/refind/icons/os_mandriva.png 755
CopyFile /efi/EFI/refind/icons/os_manjaro.png 755
CopyFile /efi/EFI/refind/icons/os_netbsd.png 755
CopyFile /efi/EFI/refind/icons/os_network.png 755
CopyFile /efi/EFI/refind/icons/os_opensuse.png 755
CopyFile /efi/EFI/refind/icons/os_redhat.png 755
CopyFile /efi/EFI/refind/icons/os_refind.png 755
CopyFile /efi/EFI/refind/icons/os_refit.png 755
CopyFile /efi/EFI/refind/icons/os_slackware.png 755
CopyFile /efi/EFI/refind/icons/os_suse.png 755
CopyFile /efi/EFI/refind/icons/os_systemd.png 755
CopyFile /efi/EFI/refind/icons/os_trusty.png 755
CopyFile /efi/EFI/refind/icons/os_ubuntu.png 755
CopyFile /efi/EFI/refind/icons/os_uefi.png 755
CopyFile /efi/EFI/refind/icons/os_unknown.png 755
CopyFile /efi/EFI/refind/icons/os_void.png 755
CopyFile /efi/EFI/refind/icons/os_win.png 755
CopyFile /efi/EFI/refind/icons/os_win8.png 755
CopyFile /efi/EFI/refind/icons/os_xenial.png 755
CopyFile /efi/EFI/refind/icons/os_xubuntu.png 755
CopyFile /efi/EFI/refind/icons/os_zesty.png 755
CopyFile /efi/EFI/refind/icons/svg/boot_win.svg 755
CopyFile /efi/EFI/refind/icons/svg/func_csr_rotate.svg 755
CopyFile /efi/EFI/refind/icons/svg/mouse.svg 755
CopyFile /efi/EFI/refind/icons/svg/os_clover.svg 755
CopyFile /efi/EFI/refind/icons/svg/os_debian.svg 755
CopyFile /efi/EFI/refind/icons/svg/os_devuan.svg 755
CopyFile /efi/EFI/refind/icons/svg/os_elementary.svg 755
CopyFile /efi/EFI/refind/icons/svg/os_gummiboot.svg 755
CopyFile /efi/EFI/refind/icons/svg/os_haiku.svg 755
CopyFile /efi/EFI/refind/icons/svg/os_legacy.svg 755
CopyFile /efi/EFI/refind/icons/svg/os_mac.svg 755
CopyFile /efi/EFI/refind/icons/svg/os_netbsd.svg 755
CopyFile /efi/EFI/refind/icons/svg/os_redhat.svg 755
CopyFile /efi/EFI/refind/icons/svg/os_refind.svg 755
CopyFile /efi/EFI/refind/icons/svg/os_refit.svg 755
CopyFile /efi/EFI/refind/icons/svg/os_win.svg 755
CopyFile /efi/EFI/refind/icons/svg/os_xenial.svg 755
CopyFile /efi/EFI/refind/icons/svg/tool_fwupdate.svg 755
CopyFile /efi/EFI/refind/icons/svg/tool_memtest.svg 755
CopyFile /efi/EFI/refind/icons/svg/tool_rescue.svg 755
CopyFile /efi/EFI/refind/icons/tool_apple_rescue.png 755
CopyFile /efi/EFI/refind/icons/tool_fwupdate.png 755
CopyFile /efi/EFI/refind/icons/tool_memtest.png 755
CopyFile /efi/EFI/refind/icons/tool_mok_tool.png 755
CopyFile /efi/EFI/refind/icons/tool_netboot.png 755
CopyFile /efi/EFI/refind/icons/tool_part.png 755
CopyFile /efi/EFI/refind/icons/tool_rescue.png 755
CopyFile /efi/EFI/refind/icons/tool_shell.png 755
CopyFile /efi/EFI/refind/icons/tool_windows_rescue.png 755
CopyFile /efi/EFI/refind/icons/transparent.png 755
CopyFile /efi/EFI/refind/icons/vol_efi.png 755
CopyFile /efi/EFI/refind/icons/vol_external.png 755
CopyFile /efi/EFI/refind/icons/vol_internal.png 755
CopyFile /efi/EFI/refind/icons/vol_net.png 755
CopyFile /efi/EFI/refind/icons/vol_optical.png 755
CreateDir /efi/EFI/refind/keys
CopyFile /efi/EFI/refind/refind.conf 755
CopyFile /efi/EFI/refind/refind_x64.efi 755
CopyFile /efi/EFI/refind/themes/refind-ambience/background.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/icons/func_about.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/icons/func_exit.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/icons/func_firmware.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/icons/func_hidden.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/icons/func_reset.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/icons/func_shutdown.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/icons/os_android.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/icons/os_antergos.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/icons/os_arch.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/icons/os_centos.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/icons/os_debian.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/icons/os_deepin.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/icons/os_elementary.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/icons/os_fedora.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/icons/os_freebsd.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/icons/os_gentoo.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/icons/os_kali.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/icons/os_kubuntu.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/icons/os_linux.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/icons/os_linuxmint.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/icons/os_mac.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/icons/os_manjaro.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/icons/os_mx.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/icons/os_neon.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/icons/os_openbsd.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/icons/os_parabola.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/icons/os_pop.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/icons/os_solus.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/icons/os_ubuntu.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/icons/os_ubuntugnome.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/icons/os_unknown.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/icons/os_void.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/icons/os_win.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/icons/os_win10.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/icons/os_win8.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/icons/os_win8_official.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/icons/os_zorin.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/icons/tool_mok_tool.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/selection_big.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/selection_small.png 755
CopyFile /efi/EFI/refind/themes/refind-ambience/theme.conf 755
CopyFile /efi/EFI/refind/vars/PreviousBoot 755
